language: ruby
rvm:
  - 2.1.2
services:
  - mysql
env:
  global:
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=coverage
    - SLACK_ORG=18f PROJECT=myusa
    - secure: K6fmrnBxiermK5s96QoOaBEhjvkLzbtSOB34FHXggiYDt8BrrH8Po+8xQ186/rx1uWrm9w4ZL/ZBZpwVaSUA9ZFwTfQ4MtO/fMF0DkL2u/pCXI6ywwRRsBCQfSPQLD5rQdStcn6rFjL8oEfAybKf4N2eTLC/IR+amp/le0SHb3gvgE9lk5E5AfVkWMRMuwjNW3h15eR9jwmDDMCAgMGEmPvIgDdqFVThALOd5cXs7SoZlAMeBrAgOGGYph3SxFicf3OBuDdNOpinECMih/Tu99FUiEUqHXLdt1vwp6ppasiV/WqjEyOXe6Kp9mHhgRJr7xFIpK8X83rfSajUiYO3xA==
install:
  - bundle install --without development
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
script:
  - RAILS_ENV=test bundle exec rake db:setup
  - bundle exec rspec --format RspecJunitFormatter -o shippable/testresults/results.xml
after_failure:
  - mysql -e 'show databases;'
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bundle exec rake --version
  - python other/slack/slack_notifier.py --project $PROJECT --org $SLACK_ORG --token $SLACK_TOKEN
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - jeremy.grahame@gsa.gov
