source 'https://api.berkshelf.com'

cookbook 'apt'
#cookbook 'bash-completion'
cookbook 'cacert'
cookbook 'cron'
cookbook 'fail2ban'
cookbook 'git'
cookbook 'hostname'
#cookbook 'imagemagick'
cookbook 'logwatch'
#cookbook 'memcached'
cookbook 'monit'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'ntp'
cookbook 'openssl'
cookbook 'ssl_certificate'
cookbook 'sudo'
#cookbook 'ubuntu'
cookbook 'users_solo'
# cookbook 'nodejs'

cookbook 'myusa', :path => './kitchen/site-cookbooks/myusa'
